package com.app.garapan.presentation.navigation

import android.net.Uri

object Routes {
    const val SPLASH = "splash"
    const val LOGIN = "login"
    const val REGISTER = "register"
    const val VERIFY_EMAIL = "verify_email?email={email}&token={token}"
    const val FORGOT_PASSWORD = "forgot_password"
    const val RESET_PASSWORD = "reset_password?email={email}&token={token}"
    const val TWO_FACTOR = "two_factor?preAuthToken={preAuthToken}"
    const val SETUP = "setup"
    const val MAIN = "main"
    const val HOME = "home"
    const val SEARCH = "search"
    const val PESAN = "pesan"
    const val POST_PROJECT = "post_project"
    const val PROFILE = "profile"
    const val PROFILE_PORTFOLIO = "profile_portfolio"
    const val PROFILE_SERVICES = "profile_services"
    const val EDIT_PROFILE = "edit_profile"
    const val EDIT_SERVICE = "edit_service/{serviceId}"
    const val ORDER_HISTORY = "order_history"
    const val SECURITY = "security"
    const val PROJECT_DETAIL = "project_detail/{projectId}"
    const val JASA_DETAIL = "jasa_detail/{jasaId}"
    const val CHAT = "chat/{workerId}"
    const val CHECKOUT = "checkout"
    const val BLOG_DETAIL = "blog_detail/{blogId}"

    fun setupRoute(role: String) = "$SETUP?role=$role"
    fun verifyEmailRoute(email: String) = "verify_email?email=${Uri.encode(email)}"
    fun resetPasswordRoute(email: String) = "reset_password?email=${Uri.encode(email)}"
    fun twoFactorRoute(preAuthToken: String) = "two_factor?preAuthToken=${Uri.encode(preAuthToken)}"
    fun projectDetailRoute(projectId: String) = "project_detail/$projectId"
    fun jasaDetailRoute(jasaId: String) = "jasa_detail/$jasaId"
    fun chatRoute(workerId: String) = "chat/$workerId"
    fun blogDetailRoute(blogId: String) = "blog_detail/$blogId"
    fun editServiceRoute(serviceId: String) = "edit_service/$serviceId"
}
