package com.app.garapan.presentation.navigation

import android.net.Uri

object Routes {
    const val SPLASH = "splash"
    const val LOGIN = "login"
    const val REGISTER = "register"
    const val VERIFY_EMAIL = "verify_email?email={email}&token={token}"
    const val FORGOT_PASSWORD = "forgot_password"
    const val RESET_PASSWORD = "reset_password?email={email}&token={token}"
    const val TWO_FACTOR = "two_factor?preAuthToken={preAuthToken}"
    const val SETUP = "setup"
    const val MAIN = "main"
    const val HOME = "home"
    const val SEARCH = "search?focus={focus}"
    const val SEARCH_FOCUS_BROWSE = "browse"
    const val SEARCH_FOCUS_JASA = "jasa"
    const val PESAN = "pesan"
    const val POST_PROJECT = "post_project"
    const val PROFILE = "profile"
    const val PROFILE_PORTFOLIO = "profile_portfolio"
    const val ADD_PORTFOLIO = "add_portfolio"
    const val EDIT_PORTFOLIO = "edit_portfolio/{portfolioId}"
    const val PROFILE_SERVICES = "profile_services"
    const val SKILLS = "skills"
    const val EDIT_PROFILE = "edit_profile"
    const val EDIT_SERVICE = "edit_service/{serviceId}"
    const val ORDER_HISTORY = "order_history"
    const val ORDER_DETAIL = "order_detail/{pesananId}"
    const val SECURITY = "security"
    const val PROJECT_DETAIL = "project_detail/{projectId}"
    const val JASA_DETAIL = "jasa_detail/{jasaId}"
    const val CHAT = "chat/{workerId}"
    const val CHECKOUT = "checkout/{jasaId}"
    const val BLOG_DETAIL = "blog_detail/{blogId}"
    const val PUBLIC_PROFILE = "public_profile/{userId}"
    const val TOP_WORKERS = "top_workers"
    const val ARTICLE_LIST = "article_list"

    fun setupRoute(role: String) = "$SETUP?role=$role"
    fun verifyEmailRoute(email: String) = "verify_email?email=${Uri.encode(email)}"
    fun resetPasswordRoute(email: String) = "reset_password?email=${Uri.encode(email)}"
    fun twoFactorRoute(preAuthToken: String) = "two_factor?preAuthToken=${Uri.encode(preAuthToken)}"
    fun projectDetailRoute(projectId: String) = "project_detail/$projectId"
    fun jasaDetailRoute(jasaId: String) = "jasa_detail/$jasaId"
    fun chatRoute(workerId: String) = "chat/$workerId"
    fun checkoutRoute(jasaId: String) = "checkout/$jasaId"
    fun orderDetailRoute(pesananId: String) = "order_detail/$pesananId"
    fun blogDetailRoute(blogId: String) = "blog_detail/$blogId"
    fun publicProfileRoute(userId: String) = "public_profile/$userId"
    fun editServiceRoute(serviceId: String) = "edit_service/$serviceId"
    fun editPortfolioRoute(portfolioId: String) = "edit_portfolio/$portfolioId"
    fun searchRoute(focus: String = SEARCH_FOCUS_BROWSE) = "search?focus=$focus"
}
